
import React from 'react';
import { Helmet } from 'react-helmet-async';
import { AlertTriangle } from 'lucide-react';

const LegalDisclaimer = () => {
  return (
    <>
      <Helmet>
        <title>Legal Disclaimer - Citation Nation</title>
        <meta name="description" content="Important legal information and disclaimers about Citation Nation's AI-powered traffic ticket analysis service." />
      </Helmet>

      <main className="min-h-screen pt-32 pb-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-black text-white mb-6">
              Legal <span className="text-[#C6FF4D]">Disclaimer</span>
            </h1>
            <p className="text-lg text-white/70">
              Important information about our service
            </p>
          </div>

          <div className="bg-[#007BFF]/10 border border-[#007BFF]/30 rounded-2xl p-6 mb-8 flex items-start gap-4">
            <AlertTriangle className="h-6 w-6 text-[#007BFF] flex-shrink-0 mt-1" />
            <div>
              <h2 className="text-lg font-bold text-white mb-2">Important Notice</h2>
              <p className="text-white/70">
                Citation Nation provides AI-powered analysis and information services. We are not a law firm and do not provide legal advice or representation.
              </p>
            </div>
          </div>

          <div className="bg-white/5 backdrop-blur-lg border border-white/10 rounded-3xl p-8 sm:p-12 space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Not Legal Advice</h2>
              <p className="text-white/70 mb-4">
                The information and analysis provided by Citation Nation is for informational purposes only and does not constitute legal advice. The use of our service does not create an attorney-client relationship between you and Citation Nation or any of its employees or contractors.
              </p>
              <p className="text-white/70">
                For legal advice specific to your situation, please consult with a licensed attorney in your jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Attorney Review and User Risk</h2>
              <p className="text-white/70 mb-4">
                When available, a licensed attorney may review the AI-generated strategy as a quality check. This review is informational and does not mean you have hired that attorney or any law firm. You are not entering into an attorney-client relationship unless you separately retain legal counsel.
              </p>
              <p className="text-white/70">
                You remain responsible for deciding how to use the information. You assume all risks associated with acting on or relying on the strategy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">AI Analysis Limitations</h2>
              <p className="text-white/70 mb-4">
                Our AI system analyzes traffic tickets based on patterns, legal precedents, and statistical data. While we strive for accuracy, the analysis is generated by artificial intelligence and may not account for all nuances of your specific case or local laws.
              </p>
              <p className="text-white/70">
                Results and success rates are based on historical data and do not guarantee specific outcomes for your case. Outcomes vary by jurisdiction, judge, facts, and evidence.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">No Guarantee of Results</h2>
              <p className="text-white/70 mb-4">
                While our strategies have proven successful in many cases, we cannot guarantee that following our analysis will result in dismissal or reduction of your traffic ticket. Court outcomes depend on many factors including:
              </p>
              <ul className="list-disc list-inside space-y-2 text-white/70 ml-4">
                <li>Local laws and court procedures</li>
                <li>Specific circumstances of your case</li>
                <li>Quality of evidence and presentation</li>
                <li>Judge and prosecutor discretion</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">User Responsibility</h2>
              <p className="text-white/70 mb-4">
                By using Citation Nation, you acknowledge that:
              </p>
              <ul className="list-disc list-inside space-y-2 text-white/70 ml-4">
                <li>You are responsible for verifying all information provided</li>
                <li>You should consult local court rules and procedures</li>
                <li>You may want to seek professional legal counsel</li>
                <li>You understand the risks involved in contesting a traffic ticket</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Service Limitations</h2>
              <p className="text-white/70">
                Citation Nation's analysis is based on the information you provide. Inaccurate, incomplete, or outdated information may result in less effective strategies. Our service does not include:
              </p>
              <ul className="list-disc list-inside space-y-2 text-white/70 ml-4 mt-4">
                <li>Court representation or appearance on your behalf</li>
                <li>Direct communication with courts or law enforcement</li>
                <li>Filing of legal documents (unless specifically arranged)</li>
                <li>Ongoing legal counsel or case management</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Refund Policy</h2>
              <p className="text-white/70">
                Our money-back guarantee applies only if we cannot identify any viable defense strategies for your ticket based on the information provided. The guarantee does not apply to unsuccessful court outcomes or user error in implementing our strategies.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Privacy & Data Security</h2>
              <p className="text-white/70">
                We take your privacy seriously and use industry-standard encryption to protect your data. However, you should be aware that transmitting information over the internet carries inherent risks. See our Privacy Policy for complete details.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Limitation of Liability</h2>
              <p className="text-white/70">
                Citation Nation and its affiliates shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our service, even if we have been advised of the possibility of such damages.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">Updates to This Disclaimer</h2>
              <p className="text-white/70">
                We reserve the right to update this disclaimer at any time. Continued use of our service after changes constitutes acceptance of the updated terms.
              </p>
            </section>

            <section className="pt-4 border-t border-white/10">
              <p className="text-white/60 text-sm">
                Last updated: December 23, 2026
              </p>
              <p className="text-white/60 text-sm mt-2">
                If you have questions about this disclaimer, please contact us at legal@citationnation.com
              </p>
            </section>
          </div>
        </div>
      </main>
    </>
  );
};

export default LegalDisclaimer;
